// One-off: converts the hero title into per-glyph SVG outlines (so it can be drawn on stroke by stroke).
// Run: node scripts/gen-title.mjs   (needs scripts/PinyonScript.ttf)
import opentype from "opentype.js"
import { readFileSync, writeFileSync } from "node:fs"

const buf = readFileSync("scripts/PinyonScript.ttf")
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength))
const SIZE = 100
// Path text built from the raw commands (opentype's own toPathData can drop a space: "25.8 0" -> "25.80").
const n1 = (v) => String(Math.round(v * 10) / 10 || 0)
function pathData(cmds) {
  return cmds
    .map((c) => {
      const pts = { M: ["x", "y"], L: ["x", "y"], Q: ["x1", "y1", "x", "y"], C: ["x1", "y1", "x2", "y2", "x", "y"], Z: [] }[c.type]
      return c.type + pts.map((k) => n1(c[k])).join(" ")
    })
    .join("")
}

function line(text) {
  const glyphs = []
  let minX = Infinity, maxX = -Infinity, minY = Infinity, maxY = -Infinity
  font.forEachGlyph(text, 0, 0, SIZE, { kerning: true }, (glyph, x, y, fontSize) => {
    const p = glyph.getPath(x, y, fontSize)
    const d = pathData(p.commands)
    if (!d) return
    const b = p.getBoundingBox()
    minX = Math.min(minX, b.x1); maxX = Math.max(maxX, b.x2); minY = Math.min(minY, b.y1); maxY = Math.max(maxY, b.y2)
    glyphs.push(d)
  })
  return { glyphs, box: [Math.floor(minX) - 4, Math.floor(minY) - 4, Math.ceil(maxX - minX) + 8, Math.ceil(maxY - minY) + 8] }
}

const lines = ["Tarbiyyah", "Conference"].map(line)
const out = `// Generated by scripts/gen-title.mjs from Pinyon Script. Do not edit.
export const TITLE_LINES: { glyphs: string[]; box: [number, number, number, number] }[] = ${JSON.stringify(lines)}
`
writeFileSync("components/site/hero/title-paths.ts", out)
console.log(lines.map((l) => `${l.glyphs.length} glyphs box ${l.box.join(",")}`).join(" | "), (out.length / 1024).toFixed(1) + "KB")
