// Turns the conference photos into the gallery's files and data:
//   node scripts/prep-photos.mjs "<source dir of .webp files>"
// Each photo is copied as public/photos/gallery/<id>.webp (re-encoded only if EXIF says to rotate it) with a 640 px
// thumbnail <id>-sm.webp beside it, and data/gallery.ts is rewritten. The id is the first 8 characters of the source
// filename. Alt text and order already in data/gallery.ts are kept, so it is safe to re-run.
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const src = process.argv[2];
if (!src || !fs.existsSync(src)) {
  console.error('usage: node scripts/prep-photos.mjs "<source dir>"');
  process.exit(1);
}
const OUT = "public/photos/gallery";
const DATA = "data/gallery.ts";

const old = fs.existsSync(DATA) ? fs.readFileSync(DATA, "utf8") : "";
const body = old.match(/galleryPhotos: GalleryPhoto\[\] = \[\n([\s\S]*?)\n\];/)?.[1] ?? "";
const kept = body ? JSON.parse(`[${body.trim().replace(/,$/, "")}]`) : [];
// Anything after the array (the home carousel's picks) is kept exactly as written.
const tail = old.match(/\n\];\n([\s\S]*)$/)?.[1] ?? "";
const order = new Map(kept.map((p, i) => [p.id, i]));
const alts = new Map(kept.map((p) => [p.id, p.alt]));

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });

const photos = [];
for (const file of fs.readdirSync(src).filter((f) => /\.webp$/i.test(f)).sort()) {
  const from = path.join(src, file);
  const id = file.slice(0, 8).toLowerCase();
  const meta = await sharp(from).metadata();
  const turned = (meta.orientation ?? 1) >= 5;
  if ((meta.orientation ?? 1) > 1) await sharp(from).rotate().webp({ quality: 82 }).toFile(path.join(OUT, `${id}.webp`));
  else fs.copyFileSync(from, path.join(OUT, `${id}.webp`));
  await sharp(from).rotate().resize({ width: 640 }).webp({ quality: 72 }).toFile(path.join(OUT, `${id}-sm.webp`));
  photos.push({ id, w: turned ? meta.height : meta.width, h: turned ? meta.width : meta.height, alt: alts.get(id) ?? "" });
}
if (new Set(photos.map((p) => p.id)).size !== photos.length) throw new Error("two source files share an 8-character prefix");
photos.sort((a, b) => (order.get(a.id) ?? 1e9) - (order.get(b.id) ?? 1e9));

fs.writeFileSync(
  DATA,
  `// Generated by scripts/prep-photos.mjs; alt text and order are edited by hand and kept on re-runs.\n` +
    `import type { GalleryPhoto } from "./types";\n\n` +
    `export const galleryPhotos: GalleryPhoto[] = [\n${photos.map((p) => `  ${JSON.stringify(p)},`).join("\n")}\n];\n${tail}`,
);
console.log(`${photos.length} photos → ${OUT}, ${DATA}`);
